### ISSUE TITLE
Requerimentos y Restricciones

### ISSUE THREAD

**Issue by afelopez** [ingratosocial/STR#1]
Es debido redactar formalmente los requerimentos y restricciones necesarios para desarrollar el proyecto escogido con anterioridad.
- [x] Requerimientos funcionales.
- [x] Requerimentos no funcionales.
- [x] Restricciones.

**Comment by smcespedesh** [comment]
En base a lo acordado en la reunion, se decidió diseñar un dispositivo que pueda medir y determinar en cantidades de potencia, el esfuerzo que se realiza mientras uno se desplaza o entrena en una bicicleta.

Nuestra arquitectura de solución se basa en un dispositivo capaz de medir mediante las revoluciones de una llanta, la velocidad y asi recomendar al conductor del vehiculo a que ritmo andar.

**Comment by smcespedesh** [comment]
Requerimientos funcionales:
1- Debe ser un dispositivo portatil que de ninguna forma afecte el funcionamiento de la bicicleta como tal.
2- Debe contar con un indicador (Una pantalla) que pueda mantener informado al conductor sobre el factor a medir.

**Comment by smcespedesh** [comment]
Requerimientos no funcionales:
1- El sensor va instalado en la llanta delantera de la bicicleta, y a su vez esta conectado al indicador.
2- El indicador esta instalado en el manubrio, y mediante su configuracion muestra constantemente al conductor cuanta potencia esta gastando en su recorrido.
3-Ademas el indicador debe avisar cuando se esta manejando bajo el ritmo recomendado, o cuando se esta sobre esforzando el conductor.

**Comment by ingratosocial** [comment]
[Requerimientos funcionales.docx](https://github.com/ingratosocial/STR/files/492179/Requerimientos.funcionales.docx)

**Comment by ingratosocial** [comment]
[Requerimientos no funcionales.docx](https://github.com/ingratosocial/STR/files/492182/Requerimientos.no.funcionales.docx)

**Comment by ingratosocial** [comment]
[Restricciones.docx](https://github.com/ingratosocial/STR/files/492188/Restricciones.docx)
