### ISSUE TITLE
Introducción

### ISSUE THREAD

**Issue by afelopez** [ingratosocial/STR#2]
Realizar un introductorio del tema seleccionado: (Sistemas de adquisición de datos "DAQ")
donde se mencione brevemente: Que es, Como es, Para que se usa.
además si se puede de una pequeña reseña histórica.

**Comment by smcespedesh** [comment]
Un sistema de adquisición de datos (SAD), consiste en la toma de muestras del mundo real (sistema analógico) para generar datos que puedan ser manipulados por un ordenador (sistema digital). Este mismo consiste principalmente, en tomar un conjunto de señales físicas, convertirlas en tensiones eléctricas y digitalizarlas de manera que se puedan procesar. Se requiere una etapa de acondicionamiento, que adecua la señal a niveles compatibles con el elemento que hace la transformación a señal digital. El elemento que hace dicha transformación es el módulo de digitalización o tarjeta de Adquisición de Datos (DAQ).
![diagrama_adquisicion_de_datos svg](https://cloud.githubusercontent.com/assets/22430340/18816661/d64e4d28-8313-11e6-895b-5ac9f787c10b.png)
¿Qué es un Dispositivo DAQ?
El hardware DAQ actúa como la interfaz entre una PC y señales del mundo exterior. Funciona principalmente como un dispositivo que digitaliza señales analógicas entrantes para que una PC pueda interpretarlas. Los tres componentes clave de un dispositivo DAQ usado para medir una señal son el circuito de acondicionamiento de señales, convertidor analógico-digital (ADC) y un bus de PC. Varios dispositivos DAQ incluyen otras funciones para automatizar sistemas de medidas y procesos. Por ejemplo, los convertidores digitales-analógicos (DACs) envían señales analógicas, las líneas de E/S digital reciben y envían señales digitales y los contadores/temporizadores cuentan y generan pulsos digitales.


Se utiliza en la industria, la investigación científica, el control de máquinas y de producción, la detección de fallas y el control de calidad entre otras aplicaciones. Esto es debido a sus multiples ventajas que incluyen entre ellas; flexibilidad de procesamiento, posibilidad de realizar las tareas en tiempo real o en análisis posteriores (a fin de analizar los posibles errores), gran capacidad de almacenamiento, rápido acceso a la información y toma de decisión, se adquieren gran cantidad de datos para poder analizar, posibilidad de emular una gran cantidad de dispositivos de medición y activar varios instrumentos al mismo tiempo, facilidad de automatización, etc.

**Comment by ingratosocial** [comment]
[introduccion primera entrega.docx](https://github.com/ingratosocial/STR/files/492158/introduccion.primera.entrega.docx)
