### ISSUE TITLE
Presentación

### ISSUE THREAD

**Issue by afelopez** [ingratosocial/STR#3]
Despues de completar la información necesaria para exponer correctamente el proyecto debemos mostrarla, para ello usaremos "powerpoint", la diapositiva debe ser minimalista y colores suaves, además de contener indices, el logo de la universidad y nuestros nombres.

**Comment by smcespedesh** [comment]
Sebastian Mauricio Cespedes Henao Cód.:812012

**Comment by ingratosocial** [comment]
[P1.pptx](https://github.com/ingratosocial/STR/files/492223/P1.pptx)
